version: '2'
services:
  postgresql:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true

      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - /Users/whalemare/Docker/lab1:/var/lib/postgresql